import pandas as pd

df = pd.read_csv("insurance.csv")
#print(df.describe())
#print(df.describe(include='all'))
#print(df.shape)
#print(df.info())
#print(df.head(5))
#print(df.tail(5))
#print(df[["age", "sex", "bmi"]].head(10))
# print(df["age"].nunique())
# print(df["age"].unique())
# print(df["age"].value_counts())
# df.drop(["age", "sex"], axis=1, inplace=True)
# df.drop(0, axis=0, inplace=True)
# print(df.loc[[1, 2], ["sex", "sex"]])
# print(df.iloc[0:5, 1:4])
# print(df.head())
# print(df.loc[[1],["sex"]])
# print(df.iloc[1, 1])
# print(df.loc[:, ["sex","sex"]])
# print(df.iloc[:, 1:2])
# print(df[df["Age"] < 50].count())
# print(df[df["Age"] < 50].count())
# print(df.loc[(df['Age'] > 30) & (df['Age'] < 50)].count())
# print(df["sex"].quantile(0.25))
print(df[["age", "bmi"]].corr())
# print(df[["sex", "bmi"]].cov())
#print(df["sex"].skew())
print(df[["age", "smoker"]].corr())
#print(df["sex"].mean())
#print(df["sex"].median())
#print(df["sex"].std())
# print(df.loc[(df['CreditScore'] < 500) & (df['Gender'] == "Female")].count())
# print(pd.DataFrame(df["CreditScore"] < 500 & df['Gender'] == "Female"))
#print(df.loc[df["sex"]].query('sex == "female"'))
print(df.query('sex == "female"'))
#print(df.query('sex == "female" and age > 30'))
#print(df["age", "sex"](df.query('sex == "female" and age > 30')))
