import pandas as pd

df = pd.read_csv("Bank_churn_modelling - Copy.csv")
#print(df.describe())
#print(df.describe(include='all'))
# print(df.shape)
# print(df.info())
#print(df.head(5))
# print(df.tail(5))
# print(df[["CreditScore", "CustomerId", "Gender"]].head(10))
# print(df["Geography"].nunique())
# print(df["Geography"].unique())
# print(df["Geography"].value_counts())
# df.drop(["Geography", "Gender"], axis=1, inplace=True)
# df.drop(0, axis=0, inplace=True)
#print(df.loc[[1, 2], ["CustomerId", "Surname"]])
#print(df.iloc[0:5, 1:4])
#print(df.head())
#print(df.loc[[1],["CustomerId"]])
#print(df.iloc[1, 1])
#print(df.loc[:, ["CustomerId","EstimatedSalary"]])
#print(df.iloc[:, 1:2])
#print(df[df["Age"] < 50].count())
#print(df[df["Age"] < 50].count())
#print(df.loc[(df['Age'] > 30) & (df['Age'] < 50)].count())
#print(df["CreditScore"].quantile(0.25))
#print(df[["CreditScore", "Balance"]].corr())
#print(df[["CreditScore", "Balance"]].cov())
#print(df.loc[(df['CreditScore'] < 500) & (df['Gender'] == "Female")].count())
#print(pd.DataFrame(df["Gender"] < 500 & df['Gender'] == "Female"))
#print(df["CreditScore", "Age"].corr())
df1 = df[["Gender","CreditScore"]]
print(df[["Gender","CreditScore"]].query('Gender == "Female"'))
#print(df["Gender"])
